### ISSUE TITLE
🐛 [BUG] - Windows compile fails (Missing deps for PebbleVault)

### ISSUE THREAD

**Issue by tristanpoland** [Far-Beyond-Dev/Horizon-Community-Edition#115]
### Description

When compiling PebbleVault on windows machines several compile time errors are encountered. This is due to some missing dependencies on windows that we know are available on Linux. Please refer to the ``installers-deb`` file in this repo to see the list of deps for Linux

### Reproduction steps

```bash
1. Clone Horizon (or any other PebbleVault dependent project)
2. ``cargo run`` or ``cargo build``
```

### OS

Windows

**Comment by IchoTM** [comment]
Hi so looking into this I do not believe that this is because of missing deps on windows. I'm on a windows machine and it seems that the way Both the PebbleVault and TerraForge deps are linked is causing them to not be identified at all.

![image](https://github.com/user-attachments/assets/07226fde-a583-4633-a667-59966c0b3ca4)

Notice how in the screenshot  both pebblevault *and* terraforge don't have any addition indicators added to them by the rust analyzer while every other dep works fine and receives status indicators

Yes I'm aware this isn't exactly a solution to the issue but I believe identifying what is similar between terraforge and pebblevault could identify why windows isn't actually finding them. My best guess would be it has something to do with the way they are added as dependencies.

**Comment by tristanpoland** [comment]
> Hi so looking into this I do not believe that this is because of missing deps on windows. I'm on a windows machine and it seems that the way Both the PebbleVault and TerraForge deps are linked is causing them to not be identified at all.
> 
> ![image](https://private-user-images.githubusercontent.com/103674864/363420806-07226fde-a583-4633-a667-59966c0b3ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTg1MzYsIm5iZiI6MTcyNTExODIzNiwicGF0aCI6Ii8xMDM2NzQ4NjQvMzYzNDIwODA2LTA3MjI2ZmRlLWE1ODMtNDYzMy1hNjY3LTU5OTY2YzBiM2NhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNTMwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDE2Y2YyM2IzZmIxODliMmYzNjg5ZDViOTU4ZTBmYzNlMmUxNjgxZWVjMDYwMzE3MzU1YWZhZDFmY2JmYjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GroisRUgsGXGC8Eqtrl4tUx76dtqQx3QPW6unBDG788)
> 
> Notice how in the screenshot both pebblevault _and_ terraforge don't have any addition indicators added to them by the rust analyzer while every other dep works fine and receives status indicators
> 
> Yes I'm aware this isn't exactly a solution to the issue but I believe identifying what is similar between terraforge and pebblevault could identify why windows isn't actually finding them. My best guess would be it has something to do with the way they are added as dependencies.

Interesting, perhaps this is sue to the different paths system on windows, but I figured that would be a non-issue

**Comment by tristanpoland** [comment]
@IchoTM Would you mind building on windows and adding the log in a comment so we have it for the record?

**Comment by IchoTM** [comment]
Will do when I get home

**Comment by IchoTM** [comment]
```
error: failed to run custom build command for `PebbleVault v0.1.0 (F:\Documents\Projects\Horizon-Community-Edition\src\crates\PebbleVault)`

Caused by:
  process didn't exit successfully: `F:\Documents\Projects\Horizon-Community-Edition\target\debug\build\PebbleVault-d7c7dd7fae6c2b9b\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at src\crates\PebbleVault\build.rs:24:23:
  Go build failed: Error { kind: NotFound, message: "program not found" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  ```

**Comment by WilliamAnimate** [comment]
> ```
> error: failed to run custom build command for `PebbleVault v0.1.0 (F:\Documents\Projects\Horizon-Community-Edition\src\crates\PebbleVault)`
> 
> Caused by:
>   process didn't exit successfully: `F:\Documents\Projects\Horizon-Community-Edition\target\debug\build\PebbleVault-d7c7dd7fae6c2b9b\build-script-build` (exit code: 101)
>   --- stderr
>   thread 'main' panicked at src\crates\PebbleVault\build.rs:24:23:
>   Go build failed: Error { kind: NotFound, message: "program not found" }
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

that panic indicates that it was unable to execute the `go` command. maybe golang isnt in your %PATH%? (or is it installed?)

**Comment by IchoTM** [comment]
Fantastic I have installed go lang  and now my instance of Horizon is just as broken as everyone else 👍

**Comment by tristanpoland** [comment]
> Fantastic I have installed go lang and now my instance of Horizon is just as broken as everyone else on Windows👍

We will get there on the Windows platform just a matter of time and finding the correct libraries.

**Comment by tristanpoland** [comment]
We are getting close, this is our current error:

```
error: failed to run custom build command for `PebbleVault v0.2.0 (C:\Users\redst\OneDrive\Documents\GitHub\Horizon-Community-Edition\src\crates\PebbleVault)`

Caused by:
  process didn't exit successfully: `C:\Users\redst\OneDrive\Documents\GitHub\Horizon-Community-Edition\target\debug\build\PebbleVault-14857e91d7e02545\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TARGET
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  go: no Go source files
  thread 'main' panicked at C:\Users\redst\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.69.4\lib.rs:622:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  ```

**Comment by WilliamAnimate** [comment]
> We are getting close, this is our current error:
> 
> ```
> error: failed to run custom build command for `PebbleVault v0.2.0 (C:\Users\redst\OneDrive\Documents\GitHub\Horizon-Community-Edition\src\crates\PebbleVault)`
> 
> Caused by:
>   process didn't exit successfully: `C:\Users\redst\OneDrive\Documents\GitHub\Horizon-Community-Edition\target\debug\build\PebbleVault-14857e91d7e02545\build-script-build` (exit code: 101)
>   --- stdout
>   cargo:rerun-if-env-changed=TARGET
>   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-pc-windows-msvc
>   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_pc_windows_msvc
>   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
> 
>   --- stderr
>   go: no Go source files
>   thread 'main' panicked at C:\Users\redst\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.69.4\lib.rs:622:31:
>   Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
> ```

hmm. have you installed the c++ clang build stuff in visual studio?

**Comment by tristanpoland** [comment]
> > We are getting close, this is our current error:
> > ```
> > error: failed to run custom build command for `PebbleVault v0.2.0 (C:\Users\redst\OneDrive\Documents\GitHub\Horizon-Community-Edition\src\crates\PebbleVault)`
> > 
> > Caused by:
> >   process didn't exit successfully: `C:\Users\redst\OneDrive\Documents\GitHub\Horizon-Community-Edition\target\debug\build\PebbleVault-14857e91d7e02545\build-script-build` (exit code: 101)
> >   --- stdout
> >   cargo:rerun-if-env-changed=TARGET
> >   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64-pc-windows-msvc
> >   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_x86_64_pc_windows_msvc
> >   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
> > 
> >   --- stderr
> >   go: no Go source files
> >   thread 'main' panicked at C:\Users\redst\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bindgen-0.69.4\lib.rs:622:31:
> >   Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
> > ```
> 
> hmm. have you installed the c++ clang build stuff in visual studio?

Should have our goal is to detect it and handle the error gracefully before compile, @haywoodspartan is going to be working on it this afternoon in the Discord with me. 

The end goal it to prompt the user to auto-install the needed components

**Comment by tristanpoland** [comment]
This was closed in error, we never had this fully functional

**Comment by Tuafo** [comment]
closing this issue because we are not using go anymore and the compile issues in win are fix it.
