### ISSUE TITLE
TODO: PebbleVault Plugin for Horizon

### ISSUE THREAD

**Issue by Tuafo** [Far-Beyond-Dev/Horizon-Community-Edition#170]
### Start Date

10/18/2024

### Summary

A Pebble Vault plugin for Horizon so we can fit better how we are going to use Pebble.

### Basic Example

Setup a PV impl to work with our API and requirements. 

### Drawbacks

None, the plugin is perfect

**Comment by tristanpoland** [comment]
@Tuafo and I will be updating the plugin to the new API in the next few days. We can than close this issue!

**Comment by tristanpoland** [comment]
This is now completed and merged, eventually the plugin will have it's very own repo and releases
